### ISSUE TITLE
Logo isn't vertically centered when "Splits I/O" text is present

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#477]
If the "Splits I/O" text in the top-left of the navbar is present (screen sizes of 1200px-width and larger) then the brand logo is higher on the screen. This appears to be due to the fact that the `a.navbar-brand` element increases in height (to accommodate the text) but the image does not (nor changes its line-height or top-margin).

Demonstration: 
![image](https://puu.sh/CjiyY/8205bf9e2f.gif)

**Comment by jhobz** [comment]
Applying the following styles seems to solve the issue:
```css
.navbar-brand {
    display: flex;
    align-items: center;
}
```
